import { defineConfig } from "oxfmt";

// One config for the whole monorepo. Each package runs `oxfmt .` from its own
// directory, and oxfmt walks up to this file. Unset options keep the defaults:
// 2-space indent, double quotes, 80-column print width.
export default defineConfig({
  ignorePatterns: [
    // Generated by `pnpm gen`. The generator owns this file's shape.
    "**/worker-configuration.d.ts",
  ],
});
