import { defineConfig } from "oxlint";

// One config for the whole monorepo. Each package runs `oxlint .` from its own
// directory, and oxlint walks up to this file. Patterns are relative to this
// directory, so they start with `**/`.
export default defineConfig({
  plugins: ["typescript", "unicorn", "oxc", "import", "node", "promise", "react"],
  categories: {
    correctness: "error",
    suspicious: "warn",
    perf: "warn",
  },
  rules: {
    // React 19 uses the automatic JSX runtime, so `React` need not be in scope.
    "react/react-in-jsx-scope": "off",
  },
  ignorePatterns: [
    // Generated by `pnpm gen`. Formatting or linting it fights the generator.
    "**/worker-configuration.d.ts",
  ],
});
