/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 134226301a6fc4ab3e95db2eab14ad7c)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	AGENT: Fetcher /* app-starter-agents */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
